# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49f68d7c2f4351c0319bd39366b2dfd8cc5803918b45b37606c75797d0ee97951233e92711151d4c9f83c6de44f625bf182b5bc769e1d1690ad1ad5d4e310a8d

test:
  secret_key_base: b0ff287714603070a6904ef17195b67cec9666be0d7bcd5f8ce0dd131c7f9b7ca25ccbf371e24c408dd3a3788e37f8057759ef94d6858a69b4b0154a7bb153b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
